version: '3.9'
services:
  backend:
    build: ./backend  # Ensure there is a Dockerfile in the backend directory
    ports:
      - '5000:5000'  # Map port 5000 on the host to port 5000 in the container
    volumes:
      - ./backend:/app  # Bind mount the backend directory to /app in the container
    environment:
      - FLASK_ENV=development  # Set the Flask environment to development

  frontend:
    build: ./frontend  # Ensure there is a Dockerfile in the frontend directory
    ports:
      - '80:3000'  # Map port 80 on the host to port 3000 in the container
    volumes:
      - ./frontend:/app  # Bind mount the frontend directory to /app in the container
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend  # Ensure the backend service is started before the frontend
